chore: Use `const char` pointer for the Artifact name getter
mendersoftware/mender-mcu pull request #112
Opened 2024-11-05 13:12 UTC by lluiscampos

2024-11-05 13:55 UTC, larsewi requested changes
In `mender_storage_get_artifact_name()` there is
```C
*artifact_name = strdup("unknown");
```
if `MENDER_NOT_FOUND`. This should be changed to reference the static string to avoid memory leak. E.g.,
```C
*artifact_name = "unknown";
```

2024-11-05 13:57 UTC, larsewi commented
There does not seem to be any caching in the POSIX version. Is this the intension?

2024-11-06 11:56 UTC, lluiscampos commented
> There does not seem to be any caching in the POSIX version. Is this the intension?

To be honest I think the value of caching in Zephyr is low: we cache artifact_name which is one string (presumably to save flash reads) but then we don't cache the provides which are multiple strings.

In POSIX, specially because it is only for testing, I don't see any value in caching.

2024-11-06 13:00 UTC, larsewi approved these changes

2024-11-06 13:46 UTC, merged